### PR TITLE
:new: :chains: cohorts: Add BX Smart Labs (@Bloinx)

### PR DESCRIPTION
**Pull request by jwflory**
This commit adds a new team profile to the Blockchain cohort. This
builds on the work done for unicef/inventory-hugo-theme#13 by
@Idadelveloper as part of unicef/inventory#78.

Screenshot of summary card for new team profile.

Screenshot of full team profile.

### CODE REVIEW

**Comment by jwflory** [comment]
Hi @nitaxmx, @andyvargtz1, & @ArturVargas, I am tagging you here for an initial review of the BX Smart Labs team profile to be published on the UNICEF Open Source Inventory site! This is a new feature on the O.S. Inventory to highlight your open source repositories and points of engagement. The goal is to make your efforts more visible and discoverable.

I need your help to verify the following information before this is officially published:

1. Verify that product summary/elevator pitch, social media links, and other company info are correct.
2. Confirm which [UN Sustainable Development Goals](https://sdgs.un.org/goals) align with your open-source product.

You can leave feedback as a comment on this Pull Request or reach out to me over email. If you are GitHub-savvy, you can also leave a proper review to "sign off" on this Pull Request too, by either approving it or requesting changes. To find the review feature, you can follow these screenshots below to start a review:

<details>

**Screenshot of the "Files changed" menu, where the review feature can be found.**

Screenshot of the "Files changed" menu, where the review feature can be found.
</details>

<details>

**Click the _Review changes_ button to add your review.**

Showing the "Review changes" menu in the upper-right corner, where feedback can be left once the menu is opened.
</details>

<details>

**Screenshot of the review interface.**

Screenshot of the review interface.
</details>

Let me know if you have questions. We can also follow up on this in our scheduled November monthly check-in.

**Comment by jwflory** [comment]
I found records from the Fund on the relevant SDGs being 5 and 8 – see commit 5878af58b4a0a7f96685537ad5cb3b4b9e1117d8. All that is needed here is a proofread on the content and summary of the Bloinx product. 🙌🏻

**Comment by jwflory** [comment]
Hey @nitaxmx, @andyvargtz1, & @ArturVargas, a friendly ping to take a look at this pull request and confirm the information or suggest any changes when you get a chance. Have a good Friday. 🙂

**Review by Idadelveloper — APPROVED** [review]
Looks good

**Comment by jwflory** [comment]
Hi @nitaxmx, @andyvargtz1, & @ArturVargas, I moved this profile into a [Google Doc](https://docs.google.com/document/d/1oXwDKug1kFApZxeQ9ay_r4DP7hdc33HkZsDyOlGQClc/edit?usp=sharing) where you can propose changes and revisions. I'll share this in our check-in call coming up too.

**Comment by jwflory** [comment]
This profile is now published on the live site: 

* https://unicef.github.io/inventory/cohorts/blockchain/
* https://unicef.github.io/inventory/cohorts/blockchain/bx-smart-labs/

**Pull request merged**
