### PR TITLE
l10n: Add base Spanish translations for Inventory

### PR DESCRIPTION
**Pull request by jwflory**
This is a first attempt at integrating multilingual content into the
Open Source Inventory. Since the theme has good support for multiple
languages, it is helpful for us to try and leverage this.

For now, I am translating Spanish since I know the language, but there
is possibility to add others in the future too.

### CODE REVIEW

**Comment by jwflory** [comment]
@Idadelveloper, could you please double-check my work and add a review? 🙌🏻

**Review by Idadelveloper — COMMENTED** [review]
@jwflory looks great to me. Maybe a comment at the top to indicate this is for Spanish just like we have for English?

**Comment by jwflory** [comment]
@Idadelveloper Good note! I took this as a chance to clean up the comment headers and make them standard in the file. Pushing a new commit now. 🚀

**Review by Idadelveloper — APPROVED** [review]
Looks good to me :)

**Comment by jwflory** [comment]
Thanks @Idadelveloper, merging! 🎬

**Pull request merged**
