### PR TITLE
:new: :tm: legal-policy: Add trademark strategy overview (closes #49)

### LINKED ISSUE #49: [CONTENT] Trademark strategies
## Content classification

_Is this about an existing page or a request for a new one?_

**Request for a new page, category, or section**.
The title of the new content is: "Trademark strategies"
If a page, it will belong to this category: "Law & Policy"

## Content description

The need for a clear trademark strategy is growing in awareness in FOSS. It is not a new need though, as shown by these existing examples:

* [Fedora Project trademark guidelines](https://fedoraproject.org/wiki/Legal:Trademark_guidelines)
* [The “Linux®” Trademark](https://www.linuxfoundation.org/trademark-usage)
* [Python Software Foundation](https://www.python.org/psf/trademarks/)

Providing guidance, tips, and advice on how to approach trademark in a sustainable way as a business is helpful advice to standardize in the Open Source Mentorship programme. Providing advice on how to distinguish a product, add-ons and other extensions (both open and closed), and other components with Open Source I.P. meets a mentorship need for the Acceleration Funding cohort.

Consider examples like the following:

* Copyleft community:
  * WordPress plug-in development community
  * Bukkit/Spigot plug-in developer ecosystem
* Open core
  * GitLab

Another helpful pointer is GitHub's Minimum Viable Governance (MVG) document on [trademark policy](https://github.com/github/MVG/blob/main/org-docs/TRADEMARKS.md).

This [Twitter poll](https://twitter.com/jwf_foss/status/1424672172631527425) available for a convenience sample on categorization.

### PR DESCRIPTION
**Pull request by jwflory**
This commit adds a new page to the "Legal & Policy" category titled,
"Trademark strategies". It includes an introduction to what trademarks
are, why they matter in an Open Source context, and it gives a specific
case study of the Moodle learning management system as a model for
trademark management and business model integration.

The purpose of this page is to provide guidance and nonbinding advice to
UNICEF Venture Fund companies in defining their own trademarks and
crafting a strategy around the management of project marks. This
compliments other content on defining project charters and governance.

Closes #49.

Screenshot preview of the full page contents rendered offline.

### CODE REVIEW

**Comment by caniszczyk** [comment]
The ASF guidelines are widely used and referenced and should be in the list imho:
http://www.apache.org/foundation/marks/

The LF manages ~1000 marks nearly and has basic usage guidelines here:
https://www.linuxfoundation.org/trademark-usage/

Also many folks essentially use trademarks as a way to drive conformance:
https://www.linuxfoundation.org/blog/driving-compatibility-with-code-and-specifications-through-conformance-trademark-programs/
https://linuxfoundation.org/blog/open-source-communities-and-trademarks-a-reprise/

**Comment by jwflory** [comment]
Thanks @caniszczyk, great suggestions! Added in commit c9127fd5fb29b29df17c6eb35acdc7b817e6a128.

**Comment by jwflory** [comment]
I'll leave this open until Monday and then merge this in if there are no other comments or feedback.

**Comment by jwflory** [comment]
Merging this in. Thanks @caniszczyk for the pointers! 🎬

**Pull request merged**
