### PR TITLE
PR for #12 Highlight related articles at the bottom of each article.

### PR DESCRIPTION
**Pull request by MuluhGodson**
From your previous comment, I optimized the code in a way that gives you the flexibility to determining what relates the articles. This is done in the front matter via the categories variable. articles in the same category will be related. Also if an image is specified in the Front matter of the article, this image will be used on the card when displaying the article as related to another, else it will just display a title and a description. I noticed each article now has a description (due to the OpenGraph PR).

In the config.toml under the general parameters, I added a new variable `article_count` which determines the maximum number of articles to be displayed in the related section. Currently, this value is set to 3 so at most 3 articles will be displayed. The current article being read is excluded from being displayed as related to itself.

### CODE REVIEW

**Comment by jwflory** [comment]
Hi @MuluhGodson, thanks for submitting this! The changes to the `inventory` repository make sense, but I noticed that you made new commits directly to the git submodule. This is a confusing step and I need to write better documentation.

First, I am curious if upstream would like to integrate these changes upstream. @somratpro, if @MuluhGodson sent this as a Pull Request to [themefisher/dot-hugo-documentation-theme](https://github.com/themefisher/dot-hugo-documentation-theme), would you be interested in accepting this contribution? This is the easiest option for me as a downstream maintainer.

However, if @somratpro prefers to not take these changes, we need to raise a Pull Request instead on the [unicef/inventory-hugo-theme](https://github.com/unicef/inventory-hugo-theme) repository. We do not want to carry custom commits to the submodule in this repository. Committing it to the inventory-hugo-theme repository improves the likelihood that others will be able to use these changes in building other downstream works.

Once the upstream theme or the UNICEF downstream fork is updated with the changes, I will update the git submodule for this repository, and then this Pull Request will be ready for a `git rebase`.

**Comment by jwflory** [comment]
Hi @MuluhGodson, feel free to send your theme changes to [unicef/inventory-hugo-theme](https://github.com/unicef/inventory-hugo-theme) to move this Pull Request forward.

**Comment by MuluhGodson** [comment]
Okay great. Let me do that

**Comment by jwflory** [comment]
Hi @MuluhGodson. I pushed commit ad452da5ae406f64a8ea2814c984a7b40fcfb611, which incorporates your changes into the git submodule theme. Could you kindly rebase this Pull Request and solve the merge conflict with latest changes in `unicef:main`? Let me know if you need pointers on rebasing if it is a new concept.

**Comment by jwflory** [comment]
Hi @MuluhGodson, is it possible to [rebase your pull request](https://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/) or open a new one instead?

**Review by jwflory — APPROVED** [review]
I did some work on rebasing this Pull Request on latest changes in `main`. I added categories to some of the other articles too. Now that the conflicts are resolved, I am merging this in.

Thanks for your work @MuluhGodson! Merged. 🌊

**Pull request merged**
