### PR TITLE
:new: :chains: cohorts: Add Xcapit (@xcapit)

### PR DESCRIPTION
**Pull request by jwflory**
This commit adds a new team profile to the Blockchain cohort. This
builds on the work done for unicef/inventory-hugo-theme#13 by
@Idadelveloper as part of unicef/inventory#78.

Screenshot of summary card for new team profile.

Screenshot of full team profile.

### CODE REVIEW

**Comment by jwflory** [comment]
Hi @torisamples, @hellyab, & @dreking, I am tagging you here for an initial review of the Leaf Global Fintech team profile to be published on the UNICEF Open Source Inventory site! This is a new feature on the O.S. Inventory to highlight your open source repositories and points of engagement. The goal is to make your efforts more visible and discoverable.

I need your help to verify the following information before this is officially published:

1. Verify that product summary/elevator pitch, social media links, and other company info are correct.
2. Confirm which [UN Sustainable Development Goals](https://sdgs.un.org/goals) align with your open-source product.

You can leave feedback as a comment on this Pull Request or reach out to me over email. If you are GitHub-savvy, you can also leave a proper review to "sign off" on this Pull Request too, by either approving it or requesting changes. To find the review feature, you can follow these screenshots below to start a review:

<details>

**Screenshot of the "Files changed" menu, where the review feature can be found.**

Screenshot of the "Files changed" menu, where the review feature can be found.
</details>

<details>

**Click the _Review changes_ button to add your review.**

Showing the "Review changes" menu in the upper-right corner, where feedback can be left once the menu is opened.
</details>

<details>

**Screenshot of the review interface.**

Screenshot of the review interface.
</details>

Let me know if you have questions. We can also follow up on this in our scheduled November monthly check-in.

**Comment by jwflory** [comment]
Hi @fboiero, @gringonivoli, & @defixcapit team, I am tagging you here for an initial review of the Xcapit team profile to be published on the UNICEF Open Source Inventory site! This is a new feature on the O.S. Inventory to highlight your open source repositories and points of engagement. The goal is to make your efforts more visible and discoverable.

I need your help to verify the following information before this is officially published:

1. Verify that product summary/elevator pitch, social media links, and other company info are correct.
2. Confirm which [UN Sustainable Development Goals](https://sdgs.un.org/goals) align with your open-source product.

You can leave feedback as a comment on this Pull Request or reach out to me over email. If you are GitHub-savvy, you can also leave a proper review to "sign off" on this Pull Request too, by either approving it or requesting changes. To find the review feature, you can follow these screenshots below to start a review:

<details>

**Screenshot of the "Files changed" menu, where the review feature can be found.**

Screenshot of the "Files changed" menu, where the review feature can be found.
</details>

<details>

**Click the _Review changes_ button to add your review.**

Showing the "Review changes" menu in the upper-right corner, where feedback can be left once the menu is opened.
</details>

<details>

**Screenshot of the review interface.**

Screenshot of the review interface.
</details>

Let me know if you have questions. We can also follow up on this in our scheduled November monthly check-in.

**Comment by jwflory** [comment]
Hey @fboiero, @gringonivoli, & @defixcapit team, a friendly ping to take a look at this pull request and confirm the information or suggest any changes when you get a chance. Have a good Friday. 🙂

**Review by Idadelveloper — APPROVED** [review]

**Comment by jwflory** [comment]
Hi @fboiero, @gringonivoli, & @defixcapit team, could you please review [this Google Doc](https://docs.google.com/document/d/1bAM-lztFZju5IeS7KgghbuuMvl4tVD3gKOy_Ak3Ihow/edit?usp=sharing) with the content and information before publishing the Xcapit profile to the UNICEF Inventory? You should have access to make comments and edits there.

https://docs.google.com/document/d/1bAM-lztFZju5IeS7KgghbuuMvl4tVD3gKOy_Ak3Ihow/edit?usp=sharing

**Comment by AntoPP** [comment]
> Hi @fboiero, @gringonivoli, & @defixcapit team, could you please review [this Google Doc](https://docs.google.com/document/d/1bAM-lztFZju5IeS7KgghbuuMvl4tVD3gKOy_Ak3Ihow/edit?usp=sharing) with the content and information before publishing the Xcapit profile to the UNICEF Inventory? You should have access to make comments and edits there.
> 
> https://docs.google.com/document/d/1bAM-lztFZju5IeS7KgghbuuMvl4tVD3gKOy_Ak3Ihow/edit?usp=sharing

Hi Justin! We've updated Xcapit profile on the gDoc https://docs.google.com/document/d/1bAM-lztFZju5IeS7KgghbuuMvl4tVD3gKOy_Ak3Ihow/edit?usp=sharing

**Comment by jwflory** [comment]
Thanks for the review @AntoPP! I pushed the changes in commit b3c16d4753837b5748330d96d08b8fc003c20619. Everything looks good to merge here, going to publish it up to the Inventory now. 🎉 🌊

**Comment by jwflory** [comment]
This profile is now published on the live site: 

* https://unicef.github.io/inventory/cohorts/blockchain/
* https://unicef.github.io/inventory/cohorts/blockchain/xcapit/

**Pull request merged**
