### PR TITLE
missions: Add a Project Charter Mission (closes #51)

### LINKED ISSUE #51: [CONTENT] New Mission: Project charter
## Content classification

_Is this about an existing page or a request for a new one?_

**Request for a new page, category, or section**.
The title of the new content is: "Project charters"
If a page, it will belong to this category: "Missions"

## Content description

In the first quarter when we work with an Innovation Fund team, we focus on the "Foundations" phase of their workplans. Some of the activities that we focus on in the Foundations phase are listed below:

* Drafting a project vision and mission
* Creating a community statement and commitment
* Deciding on a licensing strategy
* Creating interfaces for public engagement in an open work (e.g. Codes of Conduct)
* Considering trademarks and branding assets

We can consolidate these interspersed activities into a single one. This fits into the purpose of the "Missions" category, which is intended to be self-guided tools and templates for creating different pieces of an Open Source project. Defining these tasks into a public project charter is important to set goals and expectations in reality from an earlier stage in the process.

Therefore, we can create project charter mission to guide someone through this. We will use this as a "homework" assignment for the incoming 2021 Blockchain cohort joining the Innovation Fund now.

### PR DESCRIPTION
**Pull request by jwflory**
This commit adds a new Mission for Project Charters. It provides a
blueprint for what goes into defining a charter in an Open Source
context. This resource is drafted in support of the incoming August 2021
cohort in the UNICEF Innovation Fund.

Closes #51.

### CODE REVIEW

**Comment by jwflory** [comment]
I pushed commit 12b76dd24dd4cf8e2a62019eeb3c4bd3ea23ad7a with new edits. See the rendered preview below for final review:

Screenshot of the Project Charter Mission final draft as of commit 12b76dd.

**Comment by jwflory** [comment]
@funnelfiasco @spotaws Hi both, I am tagging you in this Pull Request for a totally optional review before end-of-week (Friday, 27 August). If you have 15 minutes this week to take a look, it would be greatly appreciated!

I use Fedora's mission, vision, and community statements as examples in this how-to article. A lot of the inspiration here comes from studying the Fedora Project governance and charter. Knowing that both of you have a long context of Fedora and several other Open Source communities, it would mean a lot if you could spare 15 minutes to take a look and see if anything obvious appears missing about Open Source project charters from your perspective. Thanks! 🙏🏻

**Comment by jwflory** [comment]
@GeorgLink @germonprez @ElizabethN Hi CHAOSS folks, I am tagging you in this Pull Request for a totally optional review before end-of-week (Friday, 27 August). If you have 15 minutes this week to take a look, it would be greatly appreciated!

I use the [CHAOSS project charter](https://chaoss.community/about/charter/) as a reference and also as an inspiration for formulating this instructive article about how to create a project charter. Between the three of you, I know you have a long history in CHAOSS and the Open Source world, so you all came to mind as people who might have specific thoughts or opinions on what does into creating a good project charter for an Open Source project.

It would mean a lot if you could spare 15 minutes to take a look and see if anything obvious appears missing about Open Source project charters from your perspective. Thanks! 🙏🏻

**Comment by GeorgLink** [comment]
Hi @jwflory !

I like how your focus is on bringing stakeholders to the table first and then discussing the charter with them. The steps to creating a charter are as we went through them. I'm reading the book "Get Together: How to build a community with your people" by Bailey Richardson and the first chapter says that starting a community has to begin with WHO and then WHY.

In the instructions are some pointers for an organization. It appears this is written for an organization that wants to open source its own intellectual property and start building a community. Important pointers to staffing, human resources, resource allocation, and internal process alignment could go into an open source policy that the company has because they are not pertaining to the community and thus should not be in the project charter. Maybe you can be clearer about what goes into the internal policy (company) and the project charter (community).

**Comment by germonprez** [comment]
Hi @jwflory -- thanks for sharing this. Overall, it reads really well. A few comments: 

- Editorial: There is a typo in 3.2 --> By creating an Open Source work
- I also believe that a charter can help make work more transparent for people who may not otherwise feel comfortable participating. If things like governance are clear, that helps from an inclusion perspective 
- Codes of Conduct are not just about enforcement but also to frame a welcoming environment. 
- I don't like the word 'stakeholders'. It seems so business-y :) How about 'members'?

**Comment by ElizabethN** [comment]
@jwflory thanks for including us in this review! In addition to the comments from my colleagues above, I'd recommend a focus on transparency here, as that is a cornerstone in the open source ethos. A project charter aims to shine a light on things that are often kept in a mysterious black box, especially with regard to how decisions are made and paths to leadership. A project charter also ensures that the community has a shared understanding and a single source of truth. I might include something about these points in the very first paragraph, in the "why." 

I think a project also gets bonus points for making the _process_ of crafting a project charter transparent and collaborative, and that the team crafting it is a diverse one. That helps build trust within the community and ensures underrepresented voices are included from the beginning.

**Comment by jwflory** [comment]
I incorporated edits based on the feedback from @GeorgLink, @germonprez, @ElizabethN, and @funnelfiasco. Thanks all for your contributions to this piece! 🙏🏻 I'm going to merge this in and publish it on the Open Source Inventory now.

Merging! 🌊

**Pull request merged**
