### PR TITLE
Add new stakeholder mapping exercise

### PR DESCRIPTION
**Pull request by acabunoc**
* Also added a table shortcut to the theme -- will make another PR in that repo
* Couldn't figure out how to add images, examples are just links for now

### CODE REVIEW

**Comment by acabunoc** [comment]
Short for the table is here: https://github.com/unicef/inventory-hugo-theme/pull/70

**Comment by jwflory** [comment]
I rebased into commit 1754c92bba93af7100345344ca2461b386cd9378 to include the `table` shortcode inside the git theme. The CI pipeline is expected to pass.

**Review by jwflory — CHANGES_REQUESTED** [review]
Thanks @acabunoc, I appreciate you converting this over into an O.S. Inventory page! 😀 

I have two requests before merging:

1. I suggested using another tag, see in-line comment below.
2. Could you refactor the file following the [One Sentence Per Line convention](https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line)? If you haven't written something that way before, it can take getting used to, but there are benefits of doing this for brevity and easier git diffs when reviewing edits.

Otherwise, this looks ready to go. I cloned it locally and previewed it, and it looks good.

**Review by jwflory — APPROVED** [review]
Looks great, thanks @acabunoc! 🙌🏻 Merging. 🌊

**Comment by jwflory** [comment]
This page is now published here: https://unicef.github.io/inventory/documentation/stakeholder-mapping/

**Pull request merged**
