### PR TITLE
:judge: :telescope: legal-policy: Add Creative Commons primer

### PR DESCRIPTION
**Pull request by jwflory**
This commit creates a new page that introduces the Creative Commons
license family in a UNICEF context. It introduces the licenses, explains
the difference between our preferred Free Cultural licenses and other
Creative Commons license variants, and gives the reader clarification on
how to learn more about the licenses.

This can serve as a common, public reference point for the licenses we
permit, and maybe more importantly, why.

Screenshot preview of a local rendered version of the document.

### CODE REVIEW

**Comment by jwflory** [comment]
@lacabra, @nathanbaleeta, @nathanfletcher: Tagging for a review if you have background context from the DPG side. It would be good to standardize language and messaging on Creative Commons licenses so it more closely aligns Venture Fund and DPGA on definitions. Let me know if you have questions. Thanks!

**Review by lacabra — CHANGES_REQUESTED** [review]
Thanks @jwflory for putting this page together. Everything I read looks good to me, and is in alignment with the [DPG Standard](https://github.com/DPGAlliance/DPG-Standard) and the associated [open content approved licenses](https://github.com/unicef/publicgoods-candidates/blob/main/docs/licenses.md#content).

From the list of approved licenses for open content above, I would add one more license: [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) that should be classified as "Free Cultural" works. It is an approved open content license from the point of view of the DPG Standard.

**Comment by jwflory** [comment]
Good catch @lacabra, I fixed this in commit 7d75c937dcebe90d7d8144ff152a054de8c4a39a. I think this is now ready to merge!

**Review by lacabra — APPROVED** [review]
This looks good to me.

**Comment by jwflory** [comment]
Thanks @lacabra. Merging! 🎬

**Pull request merged**
