### PR TITLE
:new: :chains: cohorts: Add Treejer (@treejer)

### PR DESCRIPTION
**Pull request by jwflory**
This commit adds a new team profile to the Blockchain cohort. This
builds on the work done for unicef/inventory-hugo-theme#13 by
@Idadelveloper as part of unicef/inventory#78.

Screenshot of summary card for new team profile.

Screenshot of full team profile.

### CODE REVIEW

**Comment by jwflory** [comment]
Hi @ermio and @amirhabibzadeh, I am tagging you here for an initial review of the Treejer team profile to be published on the UNICEF Open Source Inventory site! This is a new feature on the O.S. Inventory to highlight your open source repositories and points of engagement. The goal is to make your efforts more visible and discoverable.

I need your help to verify the following information before this is officially published:

1. Verify that product summary/elevator pitch, social media links, and other company info are correct.
2. Confirm which [UN Sustainable Development Goals](https://sdgs.un.org/goals) align with your open-source product.

You can leave feedback as a comment on this Pull Request or reach out to me over email. If you are GitHub-savvy, you can also leave a proper review to "sign off" on this Pull Request too, by either approving it or requesting changes. To find the review feature, you can follow these screenshots below to start a review:

<details>

**Screenshot of the "Files changed" menu, where the review feature can be found.**

Screenshot of the "Files changed" menu, where the review feature can be found.
</details>

<details>

**Click the _Review changes_ button to add your review.**

Showing the "Review changes" menu in the upper-right corner, where feedback can be left once the menu is opened.
</details>

<details>

**Screenshot of the review interface.**

Screenshot of the review interface.
</details>

Let me know if you have questions. We can also follow up on this in our scheduled November monthly check-in.

**Comment by jwflory** [comment]
Hey @ermio and @amirhabibzadeh, a friendly ping to take a look at this pull request and confirm the information or suggest any changes when you get a chance. Have a good Friday. 🙂

**Comment by ermio** [comment]
Hi Justin,

Sorry for the late response. I can have a quick edit if using pictures is not Ok. However, I thought maybe they help your audience better understand what Treejer is.

**SDGs**
1, 2, 9, 10, 11, 13, 15

**Description**
------------------------

Treejer (trēʒər) is an open protocol connecting funders to rural planters worldwide. The project is experimenting with cutting-edge concepts such as decentralized finance (DeFi), non-fungible tokens (NFTs) and smart contracts to unlock new opportunities for climate finance, rural development and carbon credits. The team has onboarded planters from over 10 countries located in the Latin America, Africa and Middle East. Users are enabled to make ecological and social impact even in unbanked communities.

The protocol consists of several smart contracts and two main interfaces linked to them. A web interface for funders at treejer.com and a mobile app for tree planters.

**Web Interface**
Using Treejer's web interface, users can start a forest and add trees. They see a  track the forest status and get updates from planters. The interface allows to send tree gifts to others.

App - My Forest

Each tree is represented by a clean NFT on Polygon network (Ethereum's sidechain) and is traceable by design. Real-life and on-chain attributes of the trees are accessible to everyone. Trees are individually profiled and each one has its own unique attributes, similar to collectibles. The team aims to make climate finance more fun for users.

App - Tree Profile

**Mobile App**
Rural planters use a dedicated mobile application to join Treejer, submit trees, update their status and receive rewards.

Ranger App - Treejer

**Comment by jwflory** [comment]
Thanks for the review @ermio! I pushed the changes in commit 6f7aafc3589244eef6fd746add64111f96dd0536. Everything looks good to merge here, going to publish it up to the Inventory now. 🎉 🌊

**Pull request merged**
